
=head1 COPYRIGHT

Copyright 2009, Paul Miller C<< <jettero@cpan.org> >>


... test text, please ignore

=head1 SEE ALSO

... test text, please ignore

Invalid according to L<perlpod/Formatting Codes>: 

L<Paul's Perl Modules|http://voltar.org/perl>


This should be OK:

    L<Paul's Perl Modules|http://voltar.org/perl>

This should also be OK: L<http://voltar.org/perl>

... test text, please ignore

=cut

